name: Publicar Imagen en Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DHU: ${{ secrets.DOCKER_HUB_USERNAME }}
      DHT: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
      - name: Copiar código del repositorio
        uses: actions/checkout@v4

      - name: DIAG - DOCKER_HUB_USERNAME llega vacio
        if: ${{ env.DHU == '' }}
        run: echo "vacio"

      - name: DIAG - DOCKER_HUB_TOKEN llega vacio
        if: ${{ env.DHT == '' }}
        run: echo "vacio"

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y subir imagen de la API
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mi-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/mi-api:${{ github.sha }}

      - name: Construir y subir imagen del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mi-frontend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/mi-frontend:${{ github.sha }}
